apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: backend-production-api
  namespace: backend-production
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-app-prod
    spec:
      containers:
        - name: backend-production-api
          image: backend-prod
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
  selector:
    matchLabels:
      app: backend-app-prod
  